- client/StichHub/src/components/MainLandingPage/Footer.jsx
fixed footer Responsiveness issue in ClothesCategory page #4 
Before : 
After:
> fixed footer Responsiveness issue in ClothesCategory page

- client/StichHub/package-lock.json
- client/StichHub/package.json
- client/StichHub/src/components/GoToTop.jsx
- client/StichHub/src/components/MainLandingPage/Footer.jsx
- client/StichHub/src/pages/ClothesCategory.jsx
- client/StichHub/src/pages/HomeOnlineVisit.jsx
- client/StichHub/src/pages/MainLandingPage.jsx
Added scroll to top option in some long pages having a react-icon in a circle and doesn't appear when you are already at top
> Added scroll to top option in some long pages[GSSoC'23]

- CONTRIBUTING.md
@UBA-GCOEN @Naresh-chandanbatve I have added the CONTRIBUTING.md file. 
Please review it.
> Added the Contributing Guidelines file type markdown.

- README.md
- client/StichHub/package-lock.json
- client/StichHub/src/components/MainLandingPage/NavBar.jsx
- client/StichHub/src/components/Navbar.jsx
- client/StichHub/src/components/Navbardark.jsx
- client/StichHub/src/index.css
- client/package-lock.json
This pull request addresses two specific issues related to the website's navbar: fixing its positioning and improving the hover effect.
Allow me to make more appealing UI Changes
Assign it to me
1. **Fixed Navbar Positioning**: The navbar was previously not fixed, causing it to scroll along with the page content. This pull request adds the necessary CSS code to fix the navbar to the top of the page, ensuring it remains visible at all times, even when scrolling.
2. **Improved Hover Effect**: The existing hover effect on the navbar items was not visually appealing. This pull request introduces a new hover effect that enhances the user experience. Now, when a user hovers over a navbar item, the item changes color or background, providing a clear indication of interactivity.
The screenshot …
> Fixed Navbar & Hover Effect

- .github/workflows/PR_comment.yml
> Test workflow 

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/styling.md
[New] Added new issue templates for Bug Report, Feature Request and Styling.
> [Docs]: Add bug report, feature request and styling issue templates

- client/StichHub/package-lock.json
- client/StichHub/src/components/Loginsignup/AuthTailor.jsx
- client/StichHub/src/components/Loginsignup/CustomerAuth.jsx
- server/controllers/userCustomer.js
- server/controllers/userTailor.js
Solved the issue of inserting improper user data i.e. customer and tailor data while registeration
Customer Registration:
Tailor Registration:
> User data Validation

- client/StichHub/package-lock.json
- client/StichHub/src/components/Home/Navbar.jsx
- client/StichHub/src/components/Loginsignup/AuthTailor.jsx
- client/StichHub/src/components/Loginsignup/CustomerAuth.jsx
- client/StichHub/src/components/Navbar.jsx
Solved #59 
The logo is now clickable so that user can redirect into the homepage easily.
https://github.com/UBA-GCOEN/StichHub/assets/106610322/ba75c580-ba26-4240-bef5-400bae3dbfdc
> Solved: Redirecting to homepage #59

- client/StichHub/src/components/MainLandingPage/ContactUs.jsx
> Solves issue no. #37

- client/StichHub/src/components/MainLandingPage/ContactUs.jsx
- client/StichHub/src/components/MainLandingPage/Home.jsx
- package-lock.json
Now the getting started button is fixed.
The issue was that too much padding in x was given for small screens , so i just changed padding in x to 1% so that the issue can be solved.
> #53-button-fix

- client/StichHub/src/components/MainLandingPage/About.jsx
The current implementation of the website showcases the 5 contributors in a fixed order. This pull request proposes a feature enhancement that randomizes the order of the contributors every time the website is reloaded. The goal is to provide a fresh and dynamic experience to the users without assigning any priority to the contributors.
- Added JavaScript logic to shuffle the array of contributors on website reload.
- Updated the rendering logic to dynamically generate the HTML for each contributor based on the shuffled order.
- Provides a more engaging and dynamic experience for website visitors.
- Prevents any perception of prioritization among the contributors.
- Adds an element of surprise as the order changes on every reload.
Please review the changes, assign this to me and merge …
> Added Random Position for Contributor

- client/StichHub/src/components/Loginsignup/AuthTailor.jsx
- client/StichHub/src/components/Loginsignup/CustomerAuth.jsx
- Password visibility toggle button added
- Customer auth and tailor auth signup updated
Fixes #31 
- ![image](https://github.com/UBA-GCOEN/StichHub/assets/98143022/06f5e349-d83b-4bfa-93fa-ef5d76084aaf)
- ![image](https://github.com/UBA-GCOEN/StichHub/assets/98143022/a70a177b-e3c8-4792-95de-5bf43182c0c5)
> feat: password visibility toggle button added

- client/StichHub/package-lock.json
- client/StichHub/package.json
- client/StichHub/src/components/MainLandingPage/About.css
- client/StichHub/src/components/MainLandingPage/About.jsx
Added hover icons over the images of contributors on the landing page.
I added the font awesome dependency and included it in the package.json file too which is among the committed files.
Note: Please add the correct GitHub links of the contributors in the code.
Fixes #62 
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
Here's the video preview:
https://www.loom.com/share/64b0d25cbce1412b9d167107d3123fb5
> Added hover github icons for the contributors.

- client/package-lock.json
- package-lock.json
> [ FIXES ISSUE #143 ] Remove unnecessary package-lock.json

- README.md
Added a blog section and a link to the relevant blog post in the README.md file.
Fixes # (issue)
#86
> Add Blog section to README.md

- client/StichHub/sitemap.xml
- client/StichHub/src/components/MainLandingPage/About.jsx
> Developers Profile mobile view bug resolved

- server/controllers/userCustomer.js
- server/controllers/userTailor.js
- server/package-lock.json
- server/package.json
- server/services/mail.js
Welcome mail will be send for new users after signup.
Fixes #153
> feat: mailing system added for signup

- .env.server
- client/StichHub/src/axios.js
- server/services/mail.js
The Mailing Bug has been resolved
> Welcome Mail on Registration bug resolved

- README.md
closes #162
Updated the Readme.md file with the domain section below project highlights section
> Updated README.md with Domains

- client/StichHub/src/components/TailorDetails/Tailorhead.jsx
- client/StichHub/src/pages/TailorDetails.jsx
closes #200 
Current page:
Updated page:
> [style change] Revamping About Tailor page

- client/StichHub/src/App.jsx
- client/StichHub/src/components/ErrorPage/404ErrorPage.jsx
- client/package-lock.json
> Error Page Added

- client/StichHub/src/components/MainLandingPage/Home.jsx
- client/StichHub/src/components/MainLandingPage/HowItWorks/Customers.jsx
- client/StichHub/src/components/MainLandingPage/HowItWorks/Tailors.jsx
- client/StichHub/src/components/MainLandingPage/OurServices.jsx
I have added hovering effect on buttons and images in the Home page . 
Fixes #229 
https://github.com/UBA-GCOEN/StichHub/assets/85991449/26fc852e-7e27-403c-8c93-a2c2a4bb2df8
https://github.com/UBA-GCOEN/StichHub/assets/85991449/55ec3fcd-70d6-486c-a21f-8c5785baf9ab
> Fixed : issue #229

- client/StichHub/src/common/validation.jsx
- client/StichHub/src/components/AuthError.jsx
- client/StichHub/src/components/MainLandingPage/ContactUs.jsx
Implemented inline form validation in the contact form and fixes the bug of sending empty messages from the contact form.
Fixes #308 **Contact Form Validation [BUG**]
https://github.com/UBA-GCOEN/StichHub/assets/86224794/1781b237-b885-40e3-ad5a-89694ca4b355
> Implement contact form validation

- client/StichHub/src/components/MainLandingPage/NavBar.jsx
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Issue solved: #319 
* Hardware:
* Toolchain:
* SDK:
> Ui improvement

- client/StichHub/src/components/MainLandingPage/FooterHomePage.jsx
Fixes #318
* Hardware:
* Toolchain:
* SDK:
> Improved Footer Design

- client/StichHub/src/components/Home/FilterSection.jsx
- client/StichHub/src/components/Home/TailorList.jsx
- client/StichHub/src/pages/Home.jsx
This PR contains code to make the filter dropdown functional.
Fixes #315 
https://github.com/UBA-GCOEN/StichHub/assets/86224794/9c352047-607f-452d-a525-a6345d615b37
> Filter dropdown

- .github/workflows/linting.yml
Added the prettier linter to ensure proper and uniform linting of the codebase.
* Fixes #352 
> Added linting.yml workflow

- client/StichHub/src/components/TailorDetails/ProgressM.jsx
- client/StichHub/src/components/TailorDetails/Progressbar.jsx
- client/StichHub/src/components/TailorDetails/StarRate.jsx
- client/StichHub/src/components/TailorDetails/Tailorhead.jsx
- client/StichHub/src/pages/TailorDetails.jsx
Issue Solved: #326 
@Siddhant-Patil0203  can please review it
Before
After
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
* Hardware:
* Toolchain:
* SDK:
> Card UI Improvement

- client/StichHub/src/components/MainLandingPage/Footer.jsx
The previous footer section had an <a> tag with links to tailwind.css and some other websites, which have been removed and replaced with a # symbol. In addition to that, all the social media links have been added to the footer with the attribute target=_blank and social media link src in href  . Apart from that, there was a text written in the <span> tag with the content "StichHub" and no logo. The span tag containing the text has been removed and replaced with a StichHub logo.
Fixes #333 
> clothes page footer link issue solved

- client/StichHub/src/pages/TailorProfileVerification.jsx
I have made tailor verification page optimized for mobile screens
Fixes #329 
[scrnli_21_06_2023_16-45-42.webm](https://github.com/UBA-GCOEN/StichHub/assets/92094765/a7b6ae90-c7b8-4bc7-9f3c-59657380fa27)
> #329-tailor page

- client/StichHub/src/common/validation.jsx
- client/StichHub/src/pages/TailorProfileVerification.jsx
This PR contains the code to implement the feature proposed in the issue #343  
Fixes #343 **Tailor Verification Steps are not mandotory**
https://github.com/UBA-GCOEN/StichHub/assets/86224794/7e3c62f8-5e0a-4de8-a3c7-deb55fe17512
> Tailor verification

- server/services/mail.js
Email Context and Mailid updated
> Email Context Updated

- client/StichHub/src/components/Loginsignup/AuthTailor.jsx
This PR contains the code to solve the sign in tailor button disable bug
Fixes #390 **Sign in Tailor Button is Disable**
https://github.com/UBA-GCOEN/StichHub/assets/86224794/0b836d03-e917-44cc-8bfd-3331dca36ac9
> Solve Sigin tailor button bug

- client/StichHub/src/components/MainLandingPage/ContactUs.jsx
- Improved the UI of the Contact Us Section
- Updated the `ContactUs.jsx` code
This PR is made in reference to Issue No.#339
> [UPDATE] Contact US section updated

- client/StichHub/src/components/Loginsignup/AuthTailor.jsx
- client/StichHub/src/components/Loginsignup/CustomerAuth.jsx
Solve the style bug of show password icon.
Fixes #391  **Positioning of show password icon**
> Solve show-password style bug

- client/StichHub/package-lock.json
- client/StichHub/src/components/MainLandingPage/FooterHomePage.jsx
Hey, @Siddhant-Patil0203 I have changed the hover color of Gmail and youtube. Previously it was not their official color. Now I have changed it to official colors respectively. Please review my pr and merge it. Thank you!
Fixes #439 
* Hardware:
* Toolchain:
* SDK:
> Changed the hover color of Gmail and Youtube

- client/StichHub/src/pages/Home.jsx
Hey @Siddhant-Patil0203 I have added footer on the homepage. Please review my pr and merge it. Thank you!
Fixes #436 
* Hardware:
* Toolchain:
* SDK:
> Added footer on homepage

- .github/workflows/approve_label.yml
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
* Hardware:
* Toolchain:
* SDK:
> add master access token

- server/controllers/userCustomer.js
- server/controllers/userTailor.js
Added logic to prevent creating different types of accounts with the same email.
Fixes #451 
https://github.com/UBA-GCOEN/StichHub/assets/86224794/10e239a7-8e40-453e-8fb9-5bbf819c11f5
> Same email bug fix

- server/controllers/userTailor.js
removed localhost and added updated hosting url in tailor registration verification url
> adding production url in tailor registration verification url

- client/StichHub/src/components/MainLandingPage/ContactUs.jsx
Changed a bit of CSS code to make the number input field to be near country code instead of being in middle
Fixes #559
I've tested the change in locally and it's working perfectly fine and also it's responsive for all devices
> Solved Number in the middle issue #559

- client/StichHub/src/components/Loginsignup/AuthTailor.jsx
- client/StichHub/src/components/Loginsignup/CustomerAuth.jsx
Fix the signup and login container of tailor and customer so that content is not overflowed and hidden.
Fixes #471
closes #471 **Content Overflow** 
**Full content is not displayed due to fixed height**
https://github.com/UBA-GCOEN/StichHub/assets/86224794/bec1fda7-814d-4ec5-bb34-a6589e66f599
https://github.com/UBA-GCOEN/StichHub/assets/86224794/b791ba81-ccb0-41b9-85e7-faa118b09172
> Signup-login container fix
